[package]
name = "aoc_2024"
version = "0.1.0"
edition = "2021"

[[bin]]
name = "solve"
path = "src/solve.rs"

[[bin]]
name = "download"
path = "src/download.rs"

[dependencies]
regex = "1.11.1"
reqwest = "0.12.9"

